name: cartoonize
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=openblas
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - imageio=2.5.0=py36_0
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.4.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - jupyterlab=0.35.4=py36_0
  - jupyterlab_server=0.2.0=py_0
  - libblas=3.8.0=4_openblas
  - libcblas=3.8.0=4_openblas
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=0
  - libiconv=1.15=hdd342a3_7
  - liblapack=3.8.0=4_openblas
  - libopenblas=0.3.3=hdc02c5d_3
  - libpng=1.6.36=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.10=hcb84e12_2
  - markupsafe=1.1.1=py36h1de35cc_0
  - mistune=0.8.4=py36h1de35cc_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_1
  - notebook=5.7.8=py36_0
  - olefile=0.46=py36_0
  - openblas=0.3.5=h436c29b_1001
  - openssl=1.1.1b=h1de35cc_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.4=py36_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36hb68e598_0
  - pip=19.0.3=py36_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.3.1=py36_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.14.11=py36h1de35cc_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pyzmq=18.0.0=py36h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.4.3=py36_0
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36h0a44026_0
  - sqlite=3.27.2=ha441bb4_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.2=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - gast==0.2.2
    - google-pasta==0.1.4
    - grpcio==1.19.0
    - h5py==2.8.0
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.1
    - numpy==1.16.2
    - protobuf==3.7.1
    - pyyaml==5.1
    - scipy==1.2.1
    - six==1.12.0
    - tb-nightly==1.14.0a20190301
    - tensorflow==2.0.0a0
    - tensorflow-estimator-2-0-preview==1.14.0.dev2019040300
    - tensorflow-hub==0.3.0
    - tensorflowjs==1.0.1
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019030115
    - tf-nightly-2-0-preview==2.0.0.dev20190403
    - werkzeug==0.15.2
prefix: /Users/meng.lee/anaconda3/envs/cartoonize

